vim.cmd("set noexpandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=0")
vim.cmd("set shiftwidth=4")
vim.wo.relativenumber=true
vim.g.mapleader = " "
vim.keymap.set({ "i", "v", "c" }, "<leader>jj", "<esc>")
vim.keymap.set("n", "<leader>k", "<C-o>")
vim.keymap.set("n", "<leader>j", "<C-i>")
vim.keymap.set("n", "<leader>bd", ":bd<CR>")
vim.keymap.set("n", "<leader>bj", ":bn<CR>")
vim.keymap.set("n", "<leader>bk", ":bp<CR>")
vim.keymap.set("n", "<leader>wh", "<C-w>h")
vim.keymap.set("n", "<leader>wj", "<C-w>j")
vim.keymap.set("n", "<leader>wk", "<C-w>k")
vim.keymap.set("n", "<leader>wl", "<C-w>l")
vim.keymap.set("n", "<leader>wv", "<C-w>v")
vim.keymap.set("n", "<leader>ws", "<C-w>s")
